[package]
name = "roslyn_ls"
version = "0.1.0"
authors = ["Mikhail Siarko <mikhail.siarko@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
smol = "2.0.2"
