[package]
name = "roslyn_ls"
version = "0.1.0"
authors = ["Mikhail Siarko <mikhail.siarko@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.48", features = ["macros", "net", "fs", "rt-multi-thread", "process"] }
